import { BatchPaymentSummaryTotals } from './payment-hub-api.service';
import { BatchPaymentRow } from './payment-hub-batch-insights.component';

/** Sum batch payment rows into dashboard totals (shared by finance & batch insights). */
export function sumBatchPaymentRows(rows: BatchPaymentRow[]): BatchPaymentSummaryTotals {
  const acc = rows.reduce(
    (a, r) => ({
      studentCount: a.studentCount + r.studentCount,
      totalPaid: a.totalPaid + r.totalPaid,
      totalPaidLKR: a.totalPaidLKR + r.totalPaidLKR,
      totalPaidINR: a.totalPaidINR + r.totalPaidINR,
      totalPaidUSD: a.totalPaidUSD + r.totalPaidUSD,
      totalPendingLKR: a.totalPendingLKR + r.totalPendingLKR,
      totalPendingINR: a.totalPendingINR + r.totalPendingINR,
      totalPendingUSD: a.totalPendingUSD + r.totalPendingUSD,
      totalOverdueLKR: a.totalOverdueLKR + r.totalOverdueLKR,
      totalOverdueINR: a.totalOverdueINR + r.totalOverdueINR,
      totalOverdueUSD: a.totalOverdueUSD + r.totalOverdueUSD,
      totalExpectedLKR: a.totalExpectedLKR + r.totalExpectedLKR,
      totalExpectedINR: a.totalExpectedINR + r.totalExpectedINR,
      totalExpectedUSD: a.totalExpectedUSD + r.totalExpectedUSD,
      totalDueLKR: a.totalDueLKR + r.totalDueLKR,
      totalDueINR: a.totalDueINR + r.totalDueINR,
      totalDueUSD: a.totalDueUSD + r.totalDueUSD,
      fullyPaidStudents: a.fullyPaidStudents + r.fullyPaidStudents,
      balanceStudents: a.balanceStudents + r.balanceStudents,
      overdueStudents: a.overdueStudents + r.overdueStudents,
      docsPaidStudents: a.docsPaidStudents + r.docsPaidStudents,
      visaPaidStudents: a.visaPaidStudents + r.visaPaidStudents,
      insightPaidFullLKR: a.insightPaidFullLKR + r.insightPaidFullLKR,
      insightPaidFullINR: a.insightPaidFullINR + r.insightPaidFullINR,
      insightPaidFullUSD: a.insightPaidFullUSD + r.insightPaidFullUSD,
      insightBalanceLKR: a.insightBalanceLKR + r.insightBalanceLKR,
      insightBalanceINR: a.insightBalanceINR + r.insightBalanceINR,
      insightBalanceUSD: a.insightBalanceUSD + r.insightBalanceUSD,
      insightOverdueLKR: a.insightOverdueLKR + r.insightOverdueLKR,
      insightOverdueINR: a.insightOverdueINR + r.insightOverdueINR,
      insightOverdueUSD: a.insightOverdueUSD + r.insightOverdueUSD,
      insightDocsLKR: a.insightDocsLKR + r.insightDocsLKR,
      insightDocsINR: a.insightDocsINR + r.insightDocsINR,
      insightDocsUSD: a.insightDocsUSD + r.insightDocsUSD,
      insightVisaLKR: a.insightVisaLKR + r.insightVisaLKR,
      insightVisaINR: a.insightVisaINR + r.insightVisaINR,
      insightVisaUSD: a.insightVisaUSD + r.insightVisaUSD,
      maxStudentDay: null,
      avgJourneyDay: null,
    }),
    {
      studentCount: 0,
      totalPaid: 0,
      totalPaidLKR: 0,
      totalPaidINR: 0,
      totalPaidUSD: 0,
      totalPendingLKR: 0,
      totalPendingINR: 0,
      totalPendingUSD: 0,
      totalOverdueLKR: 0,
      totalOverdueINR: 0,
      totalOverdueUSD: 0,
      totalExpectedLKR: 0,
      totalExpectedINR: 0,
      totalExpectedUSD: 0,
      totalDueLKR: 0,
      totalDueINR: 0,
      totalDueUSD: 0,
      fullyPaidStudents: 0,
      balanceStudents: 0,
      overdueStudents: 0,
      docsPaidStudents: 0,
      visaPaidStudents: 0,
      insightPaidFullLKR: 0,
      insightPaidFullINR: 0,
      insightPaidFullUSD: 0,
      insightBalanceLKR: 0,
      insightBalanceINR: 0,
      insightBalanceUSD: 0,
      insightOverdueLKR: 0,
      insightOverdueINR: 0,
      insightOverdueUSD: 0,
      insightDocsLKR: 0,
      insightDocsINR: 0,
      insightDocsUSD: 0,
      insightVisaLKR: 0,
      insightVisaINR: 0,
      insightVisaUSD: 0,
      maxStudentDay: null,
      avgJourneyDay: null,
    },
  );

  return {
    ...acc,
    collectionRateLKR:
      acc.totalExpectedLKR > 0
        ? Math.min(100, Math.round((acc.totalPaidLKR / acc.totalExpectedLKR) * 100))
        : null,
  };
}
